/**Discente.c*/
#include "../CommFiles/Discente.h"

extern struct Discente DISC_00;
extern struct Discente ACOSTA_MATEOS_FERNANDO;
extern struct Discente ALCALA_TECHACHAL_EMILIANO;
extern struct Discente BOLANIOS_VELEZ_ANGEL_GABRIEL;
extern struct Discente CABRERA_AMBROCIO_JESUS_GERSON;
extern struct Discente CALVARIO_ROJAS_GABRIEL;
extern struct Discente CESAR_CASTRO_KARINA;
extern struct Discente CORNEJO_JORDAN_JORGE_ALAIN;
extern struct Discente CRUZ_NAVA_CAROLINA_VALERIA;
extern struct Discente DOMINGUEZ_CONTRERAS_AXEL_ARIEL;
extern struct Discente ENCISO_SOLANO_JARED;
extern struct Discente GARDUNIO_SOLIS_ARES_ULISES;
extern struct Discente GOMEZ_HERNANDEZ_FRANCISCO_EMILIANO;
extern struct Discente GONZALEZ_MACIAS_ISAAC_TADEO;
extern struct Discente GUTIERREZ_HUERTA_JORGE_ANTONIO;
extern struct Discente GUTIERREZ_MARTINEZ_EMILIO;
extern struct Discente HENRIQUEZ_GARCIA_CARLOS_DIEGO;
extern struct Discente ISLAS_ORTIZ_MARINA_ESPERANZA;
extern struct Discente JIMENEZ_ROBLES_SEBASTIAN;
extern struct Discente MATUS_ALTAMIRANO_JOSE_LUIS;
extern struct Discente MORALES_RODRIGUEZ_FRANCISCO_JESUS;
extern struct Discente MUNHOZ_VEGA_YAEL_ARTURO;
extern struct Discente NAVARRETE_FUENTES_GABRIEL_OMAR;
extern struct Discente ORTEGA_ROSARIO_ABRAHAM;
extern struct Discente ORTIZ_ZAMUDIO_JESUS;
extern struct Discente PADRON_GUTIERREZ_IAN_YERED;
extern struct Discente PEREZ_MORGA_CHRISTIAN_MICHELLE;
extern struct Discente PEREZ_VAZQUEZ_DIEGO;
extern struct Discente PINEDA_TALAVERA_RICARDO;
extern struct Discente PINEDA_VILORIA_YAEL;
extern struct Discente QUINTERO_IBARRA_JUAN_LEONARDO;
extern struct Discente RAMALES_BARCENAS_JUAN;
extern struct Discente RAMIREZ_AVILA_RAUL_ALFREDO;
extern struct Discente ROSALES_CANCINO_JESUS;
extern struct Discente ROSAS_VILLA_CESAR_ALEJANDRO;
extern struct Discente SALAZAR_PEREZ_AVRIL_LIZETTE;
extern struct Discente SANCHEZ_PINIA_RAYMUNDO;
extern struct Discente SANTIAGO_TELLEZ_EDUARDO_ISRAEL;
extern struct Discente XICOTENCATL_VALENCIA_ITOM_AKAI;

/**Arreglo de apuntadores a struct Discente
 * struct Discente esta declarado en
 * struct Discente {
 *   char disc_name[SIZE_OF_DISC_NAME_ARRAY];//discente's name
 *   float caldevid[SIZE_OF_CALDEVID];       //calificacion de evidencias
 * };
 * Para cada discente su struct Discente tiene un arreglo de valores
 * reales que contiene las calificaciones de sus
 * SIZE_OF_CALDEVID/(SIZE_OF_CALDEVID-1) evidencias.
 * Del codigo de la funci\'on max_grades() en MaximunsGrades.c, se deduce
 * que
 */
static struct Discente *Disc_Arr[] = {
&DISC_00,
&ACOSTA_MATEOS_FERNANDO,
&ALCALA_TECHACHAL_EMILIANO,
//#if 0
&BOLANIOS_VELEZ_ANGEL_GABRIEL,
&CABRERA_AMBROCIO_JESUS_GERSON,
&CALVARIO_ROJAS_GABRIEL,
&CESAR_CASTRO_KARINA,
&CORNEJO_JORDAN_JORGE_ALAIN,
&CRUZ_NAVA_CAROLINA_VALERIA,
&DOMINGUEZ_CONTRERAS_AXEL_ARIEL,
&ENCISO_SOLANO_JARED,
&GARDUNIO_SOLIS_ARES_ULISES,
&GOMEZ_HERNANDEZ_FRANCISCO_EMILIANO,
&GONZALEZ_MACIAS_ISAAC_TADEO,
&GUTIERREZ_HUERTA_JORGE_ANTONIO,
&GUTIERREZ_MARTINEZ_EMILIO,
&HENRIQUEZ_GARCIA_CARLOS_DIEGO,
&ISLAS_ORTIZ_MARINA_ESPERANZA,
&JIMENEZ_ROBLES_SEBASTIAN,
&MATUS_ALTAMIRANO_JOSE_LUIS,
&MORALES_RODRIGUEZ_FRANCISCO_JESUS,
&MUNHOZ_VEGA_YAEL_ARTURO,
&NAVARRETE_FUENTES_GABRIEL_OMAR,
&ORTEGA_ROSARIO_ABRAHAM,
&ORTIZ_ZAMUDIO_JESUS,
&PADRON_GUTIERREZ_IAN_YERED,
&PEREZ_MORGA_CHRISTIAN_MICHELLE,
&PEREZ_VAZQUEZ_DIEGO,
&PINEDA_TALAVERA_RICARDO,
&PINEDA_VILORIA_YAEL,
&QUINTERO_IBARRA_JUAN_LEONARDO,
&RAMALES_BARCENAS_JUAN,
&RAMIREZ_AVILA_RAUL_ALFREDO,
&ROSALES_CANCINO_JESUS,
&ROSAS_VILLA_CESAR_ALEJANDRO,
&SALAZAR_PEREZ_AVRIL_LIZETTE,
&SANCHEZ_PINIA_RAYMUNDO,
&SANTIAGO_TELLEZ_EDUARDO_ISRAEL,
&XICOTENCATL_VALENCIA_ITOM_AKAI
//#endif // 0
};

